resume: False

train:
  start_epoch: 0
  epochs: 30
  batch_size: 1
  lr: 0.0001
  d_momentum: 0.9
  g_momentum: [0.9, 0.999]
  pixel_wt: 0.01
  content_wt: 1.0
  adv_wt: 0.05
  noise_size: 100

model:
  

device: "cuda:0"

data:
  img_res: 64
  imgs_path: '/content/drive/MyDrive/ml-100k/finesse_challenge/data/images'
  embeddings_path: '/content/drive/MyDrive/ml-100k/finesse_challenge/data/prod_embeddings.npz'

save: 'chkpts'
results: 'results'